@startuml
class Miembro_numerario{

}

class Miembro_junta_directiva

class Conferencia {

}

class Evento {

}

class Reunión_de_la_junta_directiva

class Localizacion {

}

class Persona{
}

class AAUOC{

}

Miembro_numerario--|>Persona

@enduml